# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""GNN window encoder for the Brain2Qwerty V1 ablation (Stage 1).

Motivation
----------
MEG sensors measure magnetic fields generated by dipolar currents in the
brain; the spatial correlation structure of the 306-channel Elekta layout is
governed by *physical adjacency on the scalp* (a dipole smears its signal
over nearby sensors with a smooth topographic pattern). V1's conv encoder
(``SimpleConvTimeAgg``) instead merges channels through a learned 2D-Fourier
"virtual channel" mixer: expressive, but it must *learn* the sensor topology
from data and ties that topology to a per-subject embedding table.

This module ablates Stage 1 with a graph neural network that treats the 306
sensors as nodes of a k-nearest-neighbor graph built from their physical 2D
layout coordinates (``ChannelPositions2D``). Message passing is restricted to
true spatial neighborhoods, so the inductive bias — "sensors that are close
on the scalp see correlated sources" — is baked into the architecture rather
than learned.

Design
------
* **Graph construction** (per forward pass): pairwise Euclidean distances of
  the 2D sensor positions -> k-NN adjacency (default k=8) with self-loops.
  With C=306 nodes a dense masked (C, C) attention is trivially affordable,
  so no sparse kernels or external GNN libraries are needed.
  - ``channel_positions`` of shape ``(C, 2)`` -> one graph shared by the
    whole batch.
  - ``(B, C, 2)`` -> one graph per sample *only if the layouts actually
    differ* across the batch; identical layouts are collapsed to a single
    shared graph (the common case — same MEG helmet for every trial).
  - ``None`` -> fully-connected graph (uniform neighborhood), a graceful
    degradation that keeps the module usable when positions are unavailable.
* **Node embedding**: each sensor's 25-sample window is projected by a
  ``LazyLinear`` (window length is not part of the config contract, so it is
  inferred on the first batch) plus a learned per-sensor positional vector.
* **Message passing**: L (default 3) pre-norm blocks of GAT-style multi-head
  additive attention masked to the k-NN neighborhood (scores of non-neighbors
  are set to -inf before the softmax over neighbors), each followed by a
  pre-norm FFN sublayer, with residual connections and dropout.
* **Readout**: mean-pool + max-pool over nodes -> MLP -> ``out_channels``
  per-keystroke embedding, drop-in compatible with the sentence cores.

``subject_ids`` are accepted for interface parity with
``SimpleConvTimeAgg`` but intentionally ignored: the graph is purely spatial
(sensor geometry), which is identical across subjects sharing the Elekta 306
layout — unlike V1's per-subject Fourier merger.

Limitations
-----------
* The graph is built from the 2D MNE layout projection, not true 3D sensor
  coordinates — distances at the helmet's edge are distorted.
* The graph is recomputed every forward pass and fixed within it (no learned
  or dynamic rewiring).
* The dense masked attention is O(B * C^2 * heads) in memory; fine at the
  training batch size (64) but worth remembering for very large eval batches.

Pure PyTorch, float32 where numerically sensitive (attention scores), and
runs on CPU and Apple MPS.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from neuraltrain.models.base import BaseModelConfig


# --------------------------------------------------------------------------- #
# Graph construction
# --------------------------------------------------------------------------- #
def knn_adjacency(positions: torch.Tensor, k: int) -> torch.Tensor:
    """k-NN adjacency (bool, with self-loops) from 2D sensor positions.

    Args:
        positions: (C, 2) or (N, C, 2) float tensor.
        k: number of neighbors *excluding* the node itself.

    Returns:
        Bool tensor (C, C) or (N, C, C): ``adj[..., i, j]`` is True iff j is
        one of i's k nearest neighbors (or j == i). Rows have exactly k+1
        True entries unless positions contain near-duplicates that make
        top-k ties drop a true neighbor (self-loops are always enforced).
    """
    pos = positions.float()
    dist = torch.cdist(pos, pos)  # (..., C, C)
    C = dist.size(-1)
    k = min(k, C - 1)
    idx = dist.topk(k + 1, largest=False).indices  # (..., C, k+1) incl. self
    adj = torch.zeros_like(dist, dtype=torch.bool)
    adj.scatter_(-1, idx, True)
    # enforce self-loops even under degenerate (duplicated) positions
    adj.diagonal(dim1=-2, dim2=-1).fill_(True)
    return adj


# --------------------------------------------------------------------------- #
# Masked GAT-style attention block
# --------------------------------------------------------------------------- #
class GraphAttentionBlock(nn.Module):
    """Pre-norm GAT block: masked multi-head additive attention + FFN.

    Input: node features ``x`` of shape (B, C, D) and a bool adjacency of
    shape (C, C), (1, C, C) or (B, C, C). Attention scores are computed
    GAT-style — LeakyReLU(a_dst . Wh_i + a_src . Wh_j) — and masked to -inf
    outside the neighborhood before the softmax over neighbors j.
    """

    def __init__(self, d_node: int, heads: int, dropout: float, ffn_mult: int = 2):
        super().__init__()
        if d_node % heads != 0:
            raise ValueError(f"d_node={d_node} not divisible by {heads=}")
        self.heads = heads
        self.head_dim = d_node // heads

        self.norm1 = nn.LayerNorm(d_node)
        self.w = nn.Linear(d_node, d_node, bias=False)
        self.a_src = nn.Parameter(torch.empty(heads, self.head_dim))
        self.a_dst = nn.Parameter(torch.empty(heads, self.head_dim))
        nn.init.xavier_uniform_(self.a_src)
        nn.init.xavier_uniform_(self.a_dst)
        self.out_proj = nn.Linear(d_node, d_node, bias=False)

        self.norm2 = nn.LayerNorm(d_node)
        self.ffn = nn.Sequential(
            nn.Linear(d_node, ffn_mult * d_node),
            nn.GELU(),
            nn.Linear(ffn_mult * d_node, d_node),
        )
        self.dropout = nn.Dropout(dropout)
        self.attn_dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, adj: torch.Tensor) -> torch.Tensor:
        B, C, D = x.shape
        h = self.norm1(x)
        wh = self.w(h).view(B, C, self.heads, self.head_dim)  # (B, C, H, P)

        # additive GAT scores: s[b, i, j, h] = a_dst.Wh_i + a_src.Wh_j
        s_dst = (wh * self.a_dst).sum(-1)  # (B, C, H)
        s_src = (wh * self.a_src).sum(-1)  # (B, C, H)
        scores = s_dst.unsqueeze(2) + s_src.unsqueeze(1)  # (B, C, C, H)
        scores = F.leaky_relu(scores.float(), negative_slope=0.2)

        mask = adj
        if mask.dim() == 2:
            mask = mask.unsqueeze(0)
        scores = scores.masked_fill(~mask.unsqueeze(-1), float("-inf"))
        alpha = torch.softmax(scores, dim=2)  # over neighbors j
        alpha = self.attn_dropout(alpha).to(wh.dtype)

        agg = torch.einsum("bijh,bjhp->bihp", alpha, wh).reshape(B, C, D)
        x = x + self.dropout(self.out_proj(agg))
        x = x + self.dropout(self.ffn(self.norm2(x)))
        return x


# --------------------------------------------------------------------------- #
# The encoder module
# --------------------------------------------------------------------------- #
class GnnWindowEncoderModel(nn.Module):
    """Graph-neural-network window encoder (Stage 1).

    Maps one 500 ms MEG window ``x`` of shape (B, C, T) — (B, 306, 25) for
    the V1 pipeline — to a per-keystroke embedding of shape
    ``(B, out_channels)``.

    Forward signature matches ``SimpleConvTimeAgg``:
    ``forward(x, subject_ids=None, channel_positions=None)``. ``subject_ids``
    is ignored on purpose (see module docstring); ``channel_positions`` may be
    ``(C, 2)``, ``(B, C, 2)`` or ``None``.
    """

    def __init__(self, config: "GnnWindowEncoder", n_in_channels: int, out_channels: int):
        super().__init__()
        self.out_channels = out_channels
        self.n_in_channels = n_in_channels
        self.k_neighbors = config.k_neighbors

        d = config.d_node
        # window length T is not part of the config contract -> lazy projection
        self.node_proj = nn.LazyLinear(d)
        self.node_emb = nn.Parameter(torch.zeros(1, n_in_channels, d))
        nn.init.normal_(self.node_emb, std=0.02)
        self.input_dropout = nn.Dropout(config.dropout)

        self.layers = nn.ModuleList(
            GraphAttentionBlock(d, config.heads, config.dropout)
            for _ in range(config.n_layers)
        )
        self.final_norm = nn.LayerNorm(d)

        readout_hidden = config.readout_hidden or 2 * d
        self.readout = nn.Sequential(
            nn.Linear(2 * d, readout_hidden),
            nn.GELU(),
            nn.Dropout(config.dropout),
            nn.Linear(readout_hidden, out_channels),
        )

    # ------------------------------------------------------------------ #
    def build_adjacency(
        self, channel_positions: torch.Tensor | None, batch_size: int
    ) -> torch.Tensor:
        """Bool adjacency of shape (1, C, C) or (B, C, C).

        * ``None`` -> fully-connected graph (uniform neighborhood).
        * ``(C, 2)`` -> single graph shared by the batch.
        * ``(B, C, 2)`` -> per-sample graphs, collapsed to a shared graph
          when every batch element carries the same layout (the usual case).
        """
        C = self.n_in_channels
        if channel_positions is None:
            return torch.ones(1, C, C, dtype=torch.bool)

        pos = channel_positions.detach()
        if pos.dim() == 2:
            return knn_adjacency(pos, self.k_neighbors).unsqueeze(0)
        if pos.dim() == 3:
            if pos.size(0) == 1 or bool((pos == pos[0:1]).all()):
                return knn_adjacency(pos[0], self.k_neighbors).unsqueeze(0)
            return knn_adjacency(pos, self.k_neighbors)
        raise ValueError(
            f"channel_positions must be (C, 2), (B, C, 2) or None, got {tuple(pos.shape)}"
        )

    # ------------------------------------------------------------------ #
    def forward(
        self,
        x: torch.Tensor,
        subject_ids: torch.Tensor | None = None,
        channel_positions: torch.Tensor | None = None,
    ) -> torch.Tensor:
        del subject_ids  # graph is purely spatial; identical across subjects
        B, C, _ = x.shape
        adj = self.build_adjacency(channel_positions, B).to(x.device)

        h = self.node_proj(x) + self.node_emb  # (B, C, d_node)
        h = self.input_dropout(h)
        for layer in self.layers:
            h = layer(h, adj)
        h = self.final_norm(h)

        pooled = torch.cat([h.mean(dim=1), h.max(dim=1).values], dim=-1)
        return self.readout(pooled)  # (B, out_channels)


# --------------------------------------------------------------------------- #
# Config (neuraltrain BaseModelConfig)
# --------------------------------------------------------------------------- #
class GnnWindowEncoder(BaseModelConfig):
    """Config for the GNN Stage-1 window encoder.

    ``hidden`` is required by V1's ``_build_modules`` (it is the width the
    sentence core is built at); the model is built at
    ``n_outputs == hidden``.
    """

    hidden: int = 512
    d_node: int = 128
    n_layers: int = 3
    heads: int = 4
    k_neighbors: int = 8
    dropout: float = 0.1
    readout_hidden: int | None = None  # default: 2 * d_node

    def build(self, n_in_channels: int, n_outputs: int) -> GnnWindowEncoderModel:
        return GnnWindowEncoderModel(self, n_in_channels, n_outputs)
